default: &default_settings
  twilio_callback_host: impactcallergiraffeblue.impactdialing.com
  call_end_callback_host: impactkungfupushupsclient.impactdialing.com
  incoming_callback_host: impactdialingincomingcalls.herokuapp.com
  twilio_callback_port: 80
  recording_env: heroku
  callin_phone: 4155787571

heroku:
  <<: *default_settings

heroku_staging:
  <<: *default_settings
  twilio_callback_host: impactdialing-staging.herokuapp.com
  recording_env: heroku_staging
  call_end_callback_host: impactdialing-staging.herokuapp.com
  incoming_callback_host: impactdialing-staging.herokuapp.com
  callin_phone: 6502626881

  
heroku_preproduction:
  <<: *default_settings
  twilio_callback_host: beta-twilio.impactdialing.com
  call_end_callback_host: beta-twilio.impactdialing.com
  incoming_callback_host: beta-twilio.impactdialing.com
  callin_phone: 8886215779

development:
  <<: *default_settings
  twilio_callback_host: impactdialing.showoff.io
  call_end_callback_host: impactdialing.showoff.io   
  incoming_callback_host: impactdialing.showoff.io
  recording_env: development
  callin_phone: 8582254595

test:
  <<: *default_settings
  twilio_callback_host: impactdialing.showoff.io
  call_end_callback_host: impactdialing.showoff.io   
  incoming_callback_host: impactdialing.showoff.io
  recording_env: test
