default: &default_settings
  host: impactdialing-staging.herokuapp.com
  public_host: staging.impactdialing.com
  recording_env: heroku_staging
  port: 80
  phone: 6502626881

development:
  phone: 8582254595
  <<: *default_settings

test:
  <<: *default_settings

heroku_staging:
  <<: *default_settings
  host: impactdialing-staging.herokuapp.com
  port: 80

production:
  <<: *default_settings
  host: impactdialing-staging.herokuapp.com
  port: 80

staging:
  <<: *default_settings
  phone: 8133640628
  host: staging.impactdialing.com
  port: 80

preproduction:
  <<: *default_settings
  phone: 8133640628
  host: preprod.impactdialing.com
  port: 80