default: &default_settings
  twilio_callback_host: impactcallergiraffeblue-aws.impactdialing.com
  call_end_callback_host: impactdialingcallend-aws.impactdialing.com
  incoming_callback_host: impactdialingincomingcalls-aws.impactdialing.com
  # USE IN CASE of us-east servers outage
  #twilio_callback_host: impactcallergiraffeblue-aws-west.impactdialing.com
  #call_end_callback_host: impactdialingcallend-aws-west.impactdialing.com
  #incoming_callback_host: impactdialingincomingcalls-aws-west.impactdialing.com
  twilio_callback_port: 80
  recording_env: heroku
  callin_phone: 4155787571

heroku:
  <<: *default_settings
  
aws:
  <<: *default_settings

staging: &staging
  <<: *default_settings
  recording_env: heroku_staging
  callin_phone: 6502626881
  twilio_callback_host: impactcallergiraffeblue-aws-staging.impactdialing.com
  call_end_callback_host: impactdialingcallend-aws-staging.impactdialing.com
  incoming_callback_host: impactdialingincomingcalls-aws-staging.impactdialing.com
  
heroku_staging:
  <<: *staging

aws_staging:
  <<: *staging

heroku_preproduction:
  <<: *default_settings
  twilio_callback_host: beta-twilio.impactdialing.com
  call_end_callback_host: beta-twilio.impactdialing.com
  incoming_callback_host: beta-twilio.impactdialing.com
  callin_phone: 8886215779

development:
  <<: *default_settings
  twilio_callback_host: impactdialing.showoff.io
  call_end_callback_host: impactdialing.showoff.io
  incoming_callback_host: impactdialing.showoff.io
  recording_env: development
  callin_phone: 8582254595

test:
  <<: *default_settings
  twilio_callback_host: impactdialing.showoff.io
  call_end_callback_host: impactdialing.showoff.io
  incoming_callback_host: impactdialing.showoff.io
  recording_env: test
