default: &default_settings
  host: twiliopandahiphoperaser.impactdialing.com
  public_host: www.impactdialing.com
  port: 80
  phone: 4155787571

development:
  <<: *default_settings

test:
  <<: *default_settings

heroku:
  <<: *default_settings
  port: 80

production:
  <<: *default_settings

staging:
  <<: *default_settings
  host: staging.impactdialing.com

preproduction:
  <<: *default_settings
  host: preprod.impactdialing.com

caller:
  <<: *default_settings

phonesonly:
  <<: *default_settings

