default: &default_settings
  twilio_callback_host: impactcallergiraffeblue.impactdialing.com
  twilio_callback_port: 80
  recording_env: heroku
  callin_phone: 8582254595

heroku:
  <<: *default_settings

heroku_caller:
  <<: *default_settings

heroku_staging:
  <<: *default_settings
  recording_env: heroku_staging
  callin_phone: 6502626881

heroku_preproduction:
  <<: *default_settings
  twilio_callback_host: beta-twilio.impactdialing.com
  callin_phone: 8886215779

development:
  <<: *default_settings
  twilio_callback_host: impactdialing.showoff.io
  recording_env: development

test:
  <<: *default_settings
  twilio_callback_host: impactdialing.showoff.io
  recording_env: test
