development:
  localhost:6379    
    
test:
  localhost:6379
    
heroku_staging:
  redis://10.254.238.226:6379    
  
heroku_preproduction:
  redis://10.140.76.223:6379    
  
  
heroku:
  redis://redistogo:acc06af2ea8dfd06606c3e641fe0febd@koi.redistogo.com:9090
