development:
  resque_sidekiq: redis://localhost:6379
  monitor_redis: redis://localhost:6379    
  call_flow: redis://localhost:6379
  dialer: redis://localhost:6379
  common: redis://localhost:6379
    
test:
  resque_sidekiq: localhost:6379
  monitor_redis: localhost:6379
  call_flow: localhost:6379
  dialer: localhost:6379  
  common: redis://localhost:6379
    
heroku_staging:
  call_flow: redis://10.254.238.226:6379
  dialer: redis://10.254.238.226:6379
  resque_sidekiq: redis://10.254.238.226:6379
  monitor_redis: redis://10.254.238.226:6379    
  common: redis://10.254.238.226:6379     
  
heroku_preproduction:
  call_flow: redis://10.248.206.35:6379    
  dialer: redis://10.248.206.35:6379
  resque_sidekiq: redis://10.248.206.35:6379
  monitor_redis: redis://10.248.206.35:6379    
  common: redis://10.248.206.35:6379     
  
heroku:
  redis://10.140.76.223:6379

heroku_caller:
  redis://10.140.76.223:6379

heroku_phonesonly:
  redis://10.140.76.223:6379
