process_answered_attempts:
  cron: "*/3 * * * *"
  class: AnsweredJob
  queue: answered_worker_job
  args: 
  description: "This job processes answers and stores them in a relational schema"

deactivate_monitor:
  cron: "*/5 * * * *"
  class: DeactiveUnnecessaryMonitorTabsJob
  queue: background_worker_job
  args: 
  description: "This job processes deactivates unnecessary monitor tabs"


debit_money:
  cron: "*/2 * * * *"
  class: DebiterJob
  queue: debit_worker_job
  args: 
  description: "This job debits money"


