octopus:
  environments:
    - heroku_staging
    - heroku
    - aws
    - aws_staging
    - heroku_preproduction

  test:
    read_slave1:
      adapter: mysql2
      host: localhost
      database: impactdialing_test
      username: root
      password: "123456"
      timeout: 5000
      reconnect: true

  development:
    read_slave1:
      adapter: mysql2
      host: localhost
      database: impactdialing_dev
      username: root
      password: "123456"
      timeout: 5000
      reconnect: true

  heroku_staging: &heroku_staging
    read_slave1:
      adapter: mysql2
      host: herokustaging55.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: impactdialing_heroku_staging
      username: root
      password: mypassword912481

    read_slave2:
      adapter: mysql2
      host: herokustaging55.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: impactdialing_heroku_staging
      username: root
      password: mypassword912481

    simulator_slave:
      adapter: mysql2
      host: herokustaging55.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: impactdialing_heroku_staging
      username: root
      password: mypassword912481

  aws_staging:
    <<: *heroku_staging

  heroku: &heroku
    read_slave1:
      adapter: mysql2
      host: impactdialing-production.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: heroku_production
      username: root
      password: pfsdh37sl203jq
    read_slave2:
      adapter: mysql2
      host: impactdialing-production.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: heroku_production
      username: root
      password: pfsdh37sl203jq
    simulator_slave:
      adapter: mysql2
      host: impactdialing-production.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: heroku_production
      username: root
      password: pfsdh37sl203jq

  aws:
    <<: *heroku

  heroku_preproduction:
    read_slave1:
      adapter: mysql2
      host: reports.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: heroku_production
      username: root
      password: pfsdh37sl203jq
    read_slave2:
      adapter: mysql2
      host: reports.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: heroku_production
      username: root
      password: pfsdh37sl203jq
    simulator_slave:
      adapter: mysql2
      host: reports.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: heroku_production
      username: root
      password: pfsdh37sl203jq
