octopus:
  environments:
    - heroku_staging
    - heroku
    - aws
    - aws_staging

  test:
    read_slave1:
      adapter: mysql2
      host: localhost
      database: impactdialing_test
      username: root
      password: "123456"
      timeout: 5000
      reconnect: true

  development:
    read_slave1:
      adapter: mysql2
      host: localhost
      database: impactdialing_dev
      username: root
      password: "123456"
      timeout: 5000
      reconnect: true
     
  heroku_staging: &heroku_staging  
    read_slave1:
      adapter: mysql2
      host: herokustaging55-read.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: impactdialing_heroku_staging
      username: root
      password: mypassword912481
      
    read_slave2:
      adapter: mysql2
      host: herokustaging55-read2.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: impactdialing_heroku_staging
      username: root
      password: mypassword912481

    simulator_slave:
      adapter: mysql2
      host: herokustaging55-read.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: impactdialing_heroku_staging
      username: root
      password: mypassword912481
  
  aws_staging:
    <<: *heroku_staging    

  heroku: &heroku
    read_slave1:
      adapter: mysql2
      host: heroku-production55-read.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: heroku_production
      username: root
      password: pfsdh37sl203jq
    read_slave2:
      adapter: mysql2
      host: heroku-production55-read2.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: heroku_production
      username: root
      password: pfsdh37sl203jq
    simulator_slave:
      adapter: mysql2
      host: heroku-production-simulator.cjo94dhm4pos.us-east-1.rds.amazonaws.com
      database: heroku_production
      username: root
      password: pfsdh37sl203jq


  aws:
    <<: *heroku
